name: Run Gradle Build
on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  gradle:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 25

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Package release ZIP
        run: zip -j mod-jar.zip build/libs/*.jar

      - name: Upload built mod JAR (optional)
        uses: actions/upload-artifact@v4.3.0
        with:
          name: mod-jar
          path: build/libs/*.jar

      - name: Generate Attestations
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: 'mod-jar.zip'

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Automatic release for version ${{ github.ref_name }}"
          files: mod-jar.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
